import type { SupplyDataSourceRecord } from "./types";

const fetchedAt = "2026-07-04T00:00:00.000Z";

export const SUPPLYMAP_DATA_SOURCES: SupplyDataSourceRecord[] = [
  {
    code: "kicox_factory_registry",
    providerName: "한국산업단지공단",
    datasetName: "공장등록생산정보조회서비스",
    sourceType: "MOTIE_PUBLIC",
    sourceUrl: "https://www.data.go.kr/data/15100060/standard.do",
    fetchedAt,
    license: "공공데이터포털 이용허락범위 제한 없음",
    verification: "MOCK",
    description: "등록 공장의 회사명, 주소, 업종, 생산품을 조회합니다.",
    status: "mock",
    updateCycle: "실시간 API",
    role: "국내 공장 후보 검색"
  },
  {
    code: "kicox_industrial_trends",
    providerName: "한국산업단지공단",
    datasetName: "산업동향조사 통계 조회 서비스",
    sourceType: "MOTIE_PUBLIC",
    sourceUrl: "https://www.data.go.kr/data/15152884/openapi.do",
    fetchedAt,
    license: "공공데이터포털 이용조건 준수",
    verification: "MOCK",
    description: "국가산업단지별 입주, 가동, 생산, 수출, 고용 현황을 제공합니다.",
    status: "mock",
    updateCycle: "분기",
    role: "산업단지 역량 분석"
  },
  {
    code: "kotra_trade_qa",
    providerName: "대한무역투자진흥공사",
    datasetName: "무역투자 질의응답 데이터셋",
    sourceType: "MOTIE_PUBLIC",
    sourceUrl: "https://www.data.go.kr",
    fetchedAt,
    license: "공공데이터포털 이용조건 준수",
    verification: "MOCK",
    description: "무역·투자 실무 질의응답을 RAG 근거 문서로 사용합니다.",
    status: "mock",
    updateCycle: "수시",
    role: "AI 무역상담 근거"
  },
  {
    code: "kotra_market_news",
    providerName: "대한무역투자진흥공사",
    datasetName: "해외시장뉴스",
    sourceType: "MOTIE_PUBLIC",
    sourceUrl: "https://www.data.go.kr/data/15034831/openapi.do",
    fetchedAt,
    license: "공공누리 출처표시 조건 확인 필요",
    verification: "PARTIAL",
    description: "국가별 시장동향, 규제 변화, 통관 이슈 문서를 제공합니다.",
    status: "connected",
    updateCycle: "수시",
    role: "국가·시장 위험 분석"
  },
  {
    code: "kotra_country_info",
    providerName: "대한무역투자진흥공사",
    datasetName: "국가정보",
    sourceType: "MOTIE_PUBLIC",
    sourceUrl: "https://www.kotra.or.kr",
    fetchedAt,
    license: "공공누리 출처표시 조건 확인 필요",
    verification: "MOCK",
    description: "국가별 경제, 규제, 시장 진출 기초 정보를 RAG 근거 문서로 사용합니다.",
    status: "mock",
    updateCycle: "수시",
    role: "국가·시장·거래위험 분석"
  },
  {
    code: "ksure_country_trade",
    providerName: "한국무역보험공사",
    datasetName: "국가별 업종별 위험지수",
    sourceType: "MOTIE_PUBLIC",
    sourceUrl: "https://www.data.go.kr/data/15132755/openapi.do",
    fetchedAt,
    license: "공공데이터포털 이용조건 준수",
    verification: "PARTIAL",
    description: "K-SURE RISK INDEX의 국가별·업종별 RI1~RI5 위험등급을 국가·거래위험 신호로 활용합니다.",
    status: "connected",
    updateCycle: "일 단위",
    role: "국가·거래위험 신호"
  },
  {
    code: "safety_korea",
    providerName: "국가기술표준원·Safety Korea",
    datasetName: "제품안전 인증 및 리콜 정보",
    sourceType: "MOTIE_PUBLIC",
    sourceUrl: "https://www.safetykorea.kr/openapi/api",
    fetchedAt,
    license: "출처표시 및 이용조건 확인 필요",
    verification: "PARTIAL",
    description: "AuthKey 기반 Open API로 KC 인증, 국내리콜, 국외리콜 정보를 조회합니다.",
    status: "connected",
    updateCycle: "수시",
    role: "제품안전·리콜 분석"
  },
  {
    code: "customs_requirements",
    providerName: "관세청",
    datasetName: "HS부호 및 세관장확인대상물품",
    sourceType: "OTHER_PUBLIC",
    sourceUrl: "https://www.data.go.kr/data/15101589/openapi.do",
    fetchedAt,
    license: "공공데이터포털 이용조건 준수",
    verification: "PARTIAL",
    description: "HS 후보별 세관장확인대상 여부, 확인법령, 요건승인기관, 확인서류를 확인합니다.",
    status: "connected",
    updateCycle: "수시",
    role: "통관요건 분석"
  },
  {
    code: "customs_trade_stats",
    providerName: "관세청",
    datasetName: "품목별 국가별 수출입실적",
    sourceType: "OTHER_PUBLIC",
    sourceUrl: "https://www.data.go.kr/data/15100475/openapi.do",
    fetchedAt,
    license: "공공데이터포털 이용조건 준수",
    verification: "PARTIAL",
    description: "HS코드와 국가코드 기준 월별 수입액, 수입중량, 수출액, 무역수지를 조회해 국가·시장 의존도 보조 신호로 활용합니다.",
    status: "connected",
    updateCycle: "월 1회",
    role: "시장규모·수입의존도 분석"
  },
  {
    code: "unipass_hs_code",
    providerName: "관세청 UNI-PASS",
    datasetName: "HS부호검색",
    sourceType: "OTHER_PUBLIC",
    sourceUrl: "https://unipass.customs.go.kr:38010/ext/rest/hsSgnQry/searchHsSgn",
    fetchedAt,
    license: "관세청 UNI-PASS Open API 이용조건 준수",
    verification: "PARTIAL",
    description: "물품명 또는 HS부호 기준 HS 10단위 후보, 품명, 세율구분 정보를 조회합니다.",
    status: "connected",
    updateCycle: "수시",
    role: "HS 후보 보강 및 품목분류 확인"
  },
  {
    code: "unipass_customs_requirements",
    providerName: "관세청 UNI-PASS",
    datasetName: "세관장확인대상 물품 조회",
    sourceType: "OTHER_PUBLIC",
    sourceUrl: "https://unipass.customs.go.kr:38010/ext/rest/ccctLworCdQry/retrieveCcctLworCd",
    fetchedAt,
    license: "관세청 UNI-PASS Open API 이용조건 준수",
    verification: "PARTIAL",
    description: "HS부호별 세관장확인대상 법령, 확인서류, 요건승인기관을 조회합니다.",
    status: "connected",
    updateCycle: "수시",
    role: "수입요건·확인법령 분석"
  },
  {
    code: "unipass_tariff_rate",
    providerName: "관세청 UNI-PASS",
    datasetName: "관세율 기본 조회",
    sourceType: "OTHER_PUBLIC",
    sourceUrl: "https://unipass.customs.go.kr:38010/ext/rest/trrtQry/retrieveTrrt",
    fetchedAt,
    license: "관세청 UNI-PASS Open API 이용조건 준수",
    verification: "PARTIAL",
    description: "HS부호별 기본세율, WTO, FTA 등 관세율 구분별 세율 정보를 조회합니다.",
    status: "connected",
    updateCycle: "수시",
    role: "예상 관세율·FTA 검토"
  },
  {
    code: "unipass_fx_rate",
    providerName: "관세청 UNI-PASS",
    datasetName: "관세환율 정보",
    sourceType: "OTHER_PUBLIC",
    sourceUrl: "https://unipass.customs.go.kr:38010/ext/rest/trifFxrtInfoQry/retrieveTrifFxrtInfo",
    fetchedAt,
    license: "관세청 UNI-PASS Open API 이용조건 준수",
    verification: "PARTIAL",
    description: "수입·수출 관세평가에 쓰는 관세환율 정보를 통화별로 조회합니다.",
    status: "connected",
    updateCycle: "주 단위",
    role: "수입 원가·환율 리스크 보조 분석"
  },
  {
    code: "unipass_hs_navigation",
    providerName: "관세청 UNI-PASS",
    datasetName: "HS CODE 내비게이션",
    sourceType: "OTHER_PUBLIC",
    sourceUrl: "https://unipass.customs.go.kr:38010/ext/rest/cmtrStatsQry/retrieveCmtrStats",
    fetchedAt,
    license: "관세청 UNI-PASS Open API 이용조건 준수",
    verification: "PARTIAL",
    description: "HS 10단위 신고 내역을 건수 순위로 집계한 품목 후보 내비게이션 데이터를 조회합니다.",
    status: "connected",
    updateCycle: "수시",
    role: "HS 후보·시장 품목명 보강"
  },
  {
    code: "mfds_overseas_factory",
    providerName: "식품의약품안전처",
    datasetName: "수입식품 해외제조업소 정보",
    sourceType: "OTHER_PUBLIC",
    sourceUrl: "https://www.data.go.kr/data/15073967/openapi.do",
    fetchedAt,
    license: "공공데이터포털 이용조건 준수",
    verification: "PARTIAL",
    description: "수입식품 관련 해외 제조업소를 보조 후보로 제공합니다.",
    status: "connected",
    updateCycle: "수시",
    role: "해외 공장 보조 레이어"
  },
  {
    code: "private_global_factory",
    providerName: "사용자·민간 공급망 데이터",
    datasetName: "해외 공장 통합 보조 데이터",
    sourceType: "PRIVATE",
    sourceUrl: "https://www.google.com/maps",
    fetchedAt,
    license: "각 원천 서비스 약관 적용",
    verification: "CHECK_REQUIRED",
    description: "민간 디렉터리와 지도에서 수집된 해외 후보이며 개별 검증이 필요합니다.",
    status: "connected",
    updateCycle: "사용자 요청",
    role: "해외 후보 확장"
  },
  {
    code: "user_uploaded_suppliers",
    providerName: "사용자 업로드",
    datasetName: "공급업체 목록·견적서·카탈로그",
    sourceType: "USER_UPLOAD",
    sourceUrl: "about:blank",
    fetchedAt,
    license: "사용자 보유 권한 및 원문 이용조건 확인 필요",
    verification: "CHECK_REQUIRED",
    description: "사용자가 업로드한 공급업체 목록, 견적서, 카탈로그를 후보 보강 데이터로 사용합니다.",
    status: "planned",
    updateCycle: "사용자 업로드 시",
    role: "사용자 보유 후보 보강"
  }
];

export function supplySource(code: string): SupplyDataSourceRecord {
  const source = SUPPLYMAP_DATA_SOURCES.find((item) => item.code === code);
  if (!source) throw new Error("Unknown SupplyMap data source: " + code);
  return source;
}
